name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.4.1'

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        install-only: true

    - name: Run Mage
      uses: magefile/mage-action@v1
      with:
        version: latest
        args: build
